services:
  adguard:
    image: adguard/adguardhome
    container_name: AdGuard
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    network_mode: host
    volumes:
      - adguard_config:/opt/adguardhome/conf:rw
      - adguard_data:/opt/adguardhome/work:rw
    environment:
      TZ: Asia/Ho_Chi_Minh
volumes:
 adguard_config:
 adguard_data:
