version: '3'

networks:
  rustdesk-net:
    external: false

services:
  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r your-domain:21117 #Replace your domain or your IP Public
    volumes:
      - docker_rdhbbs:/root
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: always

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - docker_rdhbbr:/root
    networks:
      - rustdesk-net
    restart: always
volumes:
 docker_rdhbbs:
 docker_rdhbbr:
